[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "local-coding-agent"
version = "0.1.0"
description = "Local Coding Agent (LCA) CLI"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "LCA", email = "dev@example.com" }]
license = { text = "MIT" }
dependencies = [
  "typer[all]>=0.12.0",
  "rich>=13.7.0",
  "openai>=1.30.0",
  "python-dotenv>=1.0.1",
  "pydantic>=2.7.0"
]

[project.scripts]
lca = "agent.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["agent*"]
